apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nginx
            tier: nginx
    template:
        metadata:
            labels:
                app: nginx
                tier: nginx
        spec:
          containers:
          - name: back
            image: debian
            command: [ "sleep", "3600" ]
          - name: nginx
            image: acdcb/diploma
            imagePullPolicy: Always
            ports:
            - name: http
              containerPort: 8080
            volumeMounts:
            - name: data
              mountPath: /mnt/nfs
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: fileshare
---
apiVersion: v1
kind: Service
metadata:
    name: nginx
spec:
    type: NodePort
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
    selector:
        app: nginx
        tier: nginx
