apiVersion: apps/v1
kind: Deployment
metadata:
    name: mynginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mynginx
            tier: mynginx
    template:
        metadata:
            labels:
                app: mynginx
                tier: mynginx
        spec:
          containers:
          - name: back
            image: debian
            command: [ "sleep", "3600" ]
          - name: mynginx
            image: acdcb/diploma
            imagePullPolicy: Always
            ports:
            - name: http
              containerPort: 80
            volumeMounts:
            - name: data
              mountPath: /mnt/nfs
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: fileshare
---
apiVersion: v1
kind: Service
metadata:
    name: mynginx
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    selector:
        app: mynginx
        tier: mynginx
